language: java
jdk:
  - openjdk13
deploy:
  provider: heroku
  api_key:
    secure: N3QDBW6b0G4bcbELV6vOulZVnw1X14vx1SiLvZdrvRvn4CHWO6qzRzPReCxrCbvAV9T0kYZGvN5Qeu9nZ+C6FVqOfJgacZoXcBbTpVECDftXrqMsz6yr9RGAlpsaW7GQDXyACT6HmZc24KOjQb6FVJGtw3xtcx7H9fGy0jyqhX66gpsGki/Xoyhde05huPMDiIu3ekzHnenoeVPamtX1xjLH3PB7tWWHaO3wzJERu2A1C2Np5z0Ca32UUahh5qhVY0Tq6DVNDfyPy72qDzhtqyBhMX5nbiVEjrr0PLF4M3mVecnTzk7TWF2fZiX7OcEhpb0vSsrlkxxf+kfP8TG+IerlZRSw+CW1tB745gou0EOh1KdIfX4S4HxcAxGU4GZLZqQSg5EvfziYMyM5hpOIMG7kMEoZOczamDWD9P8QUjMh47dAeZJsrcVIuquRt8o6CaNLPhuaM0yi8WDiXn6VaSwiFVXg5HXgaQjgzf8eR+UOHy0q3+QShBHn9zTyomf7X7uyfst4QnLYqanzDN+F35KODTX4BXyaRjBVKkttWsKOQzLEctFsDDE26XylXDYMQ01RFIXhECXagh1sQbF1xoEkS/3DE6oeELmT0dguUW3t2xa0MPbNwYSlUy9Jz1YgnoktaBcUZgvg9FLM7tGMiz/1LM6ZbQZPpul4gD4i6Lc=
  app: elite-four
